"""
Session 18: SHA Lie algebra — NEW FRAMEWORK attempt.

After 17 sessions of incremental work, I'm taking a more ambitious step:
attempt to construct a new algebraic object capturing SHA's rotation operators.

DEFINITION (proposed):
  Let L be the Z_2-Lie subalgebra of End(H¹(F_2[s]/(s^{32}))) generated by
  {Σ_0 - I, Σ_1 - I} with bracket [A, B] = AB - BA = AB + BA (char 2).

  Σ_0, Σ_1 are our computed 16×16 matrices over F_2.

TO COMPUTE:
  1. [Σ_0 - I, Σ_1 - I] directly
  2. Iterate bracket: [L, L], [L, [L,L]], ... (lower central series)
  3. Determine if L is nilpotent, abelian, or something else
  4. Structural implications

This is a GENUINE new algebraic structure for SHA, not in methodology.
"""

import numpy as np
from session_14_sigma0 import build_sigma_0_matrix_on_H1, gf2_rank, compute_kernel, lucas_expansion
from session_15_joint import build_sigma_matrix


def commutator(A, B):
    """Matrix commutator over F_2: [A, B] = AB + BA."""
    return ((A @ B) ^ (B @ A)) & 1


def iterate_brackets(generators, max_depth=10):
    """Iteratively apply brackets to generators, collect all new matrices.
    Returns list of matrices forming Lie algebra (up to given depth)."""
    L = list(generators)
    # Reduce by rank/linear combinations over F_2
    for _ in range(max_depth):
        new_matrices = []
        for i, A in enumerate(L):
            for j, B in enumerate(L):
                if i < j:  # [A, B] and [B, A] give same up to sign (char 2: same)
                    C = commutator(A, B)
                    if C.sum() > 0:  # non-zero
                        new_matrices.append(C)
        # Keep only NEW matrices (not in linear span of L already)
        L_prev = L.copy()
        for C in new_matrices:
            if not is_in_span(L, C):
                L.append(C)
        if len(L) == len(L_prev):
            break  # no new, closed under brackets
    return L


def is_in_span(matrices, C):
    """Is C in F_2-linear span of list of matrices?"""
    if not matrices:
        return C.sum() == 0
    n_rows, n_cols = C.shape
    # Vectorize matrices
    vectors = np.array([m.flatten() for m in matrices], dtype=np.uint8)
    C_flat = C.flatten()
    # Check if C_flat is in row span of vectors
    augmented = np.vstack([vectors, [C_flat]])
    rank_before = gf2_rank(vectors.copy())
    rank_after = gf2_rank(augmented.copy())
    return rank_before == rank_after


def linearly_independent_subset(matrices):
    """Extract linearly independent subset using Gaussian elimination."""
    if not matrices:
        return []
    vectors = np.array([m.flatten() for m in matrices], dtype=np.uint8)
    # Row reduce
    n, m = vectors.shape
    reduced = vectors.copy()
    pivot_rows = []
    r = 0
    for c in range(m):
        if r >= n: break
        pivot = None
        for rr in range(r, n):
            if reduced[rr, c] == 1:
                pivot = rr; break
        if pivot is None: continue
        if pivot != r:
            reduced[[r, pivot]] = reduced[[pivot, r]]
            pivot_rows.append(pivot)
        else:
            pivot_rows.append(r)
        for rr in range(n):
            if rr != r and reduced[rr, c] == 1:
                reduced[rr] ^= reduced[r]
        r += 1
    return pivot_rows


def main_analysis():
    # Get Σ_0 and Σ_1 matrices
    M_s0, odd_positions, _ = build_sigma_matrix([2, 13, 22], n=32)
    M_s1, _, _ = build_sigma_matrix([6, 11, 25], n=32)

    # N_0 = Σ_0 - I, N_1 = Σ_1 - I (nilpotent parts)
    I = np.eye(16, dtype=np.uint8)
    N0 = (M_s0 ^ I) & 1
    N1 = (M_s1 ^ I) & 1

    print("=== SHA Lie algebra L = ⟨Σ_0 - I, Σ_1 - I⟩ over F_2 ===\n")
    print(f"  Generators: N_0 = Σ_0 - I, N_1 = Σ_1 - I (nilpotent)")
    print(f"  rank(N_0) = {gf2_rank(N0.copy())}")
    print(f"  rank(N_1) = {gf2_rank(N1.copy())}")

    # Compute [N_0, N_1]
    C01 = commutator(N0, N1)
    print(f"\n  [N_0, N_1] = N_0 N_1 + N_1 N_0 (char 2)")
    print(f"  rank([N_0, N_1]) = {gf2_rank(C01.copy())}")

    # Is [N_0, N_1] = 0? (commute?)
    if C01.sum() == 0:
        print(f"  N_0 and N_1 COMMUTE — Lie algebra is abelian")
        return

    print(f"  N_0 and N_1 DO NOT commute — non-trivial Lie algebra")

    # Iterate to build Lie algebra
    L = iterate_brackets([N0, N1], max_depth=20)
    print(f"\n  After bracket closure: {len(L)} generators (with duplicates via span)")

    # Find linearly independent subset
    indep_indices = linearly_independent_subset(L)
    print(f"  Linearly independent: {len(indep_indices)} matrices")
    print(f"  Dimension of Lie algebra L: {len(indep_indices)}")

    # Show ranks of each element
    L_indep = [L[i] for i in indep_indices]
    print(f"\n  Ranks of basis elements: {[gf2_rank(m.copy()) for m in L_indep]}")

    # Compute lower central series
    print(f"\n=== Lower central series ===")
    print(f"  L^1 = L, dim = {len(indep_indices)}")

    L_current = L_indep
    for depth in range(2, 10):
        # L^{k+1} = [L, L^k]
        new_brackets = []
        for A in L_indep:  # L
            for B in L_current:  # L^k
                C = commutator(A, B)
                if C.sum() > 0:
                    new_brackets.append(C)
        # Find independent subset
        if not new_brackets:
            print(f"  L^{depth} = 0. Lie algebra is NILPOTENT of class {depth - 1}.")
            break
        indep = linearly_independent_subset(new_brackets)
        L_next = [new_brackets[i] for i in indep]
        print(f"  L^{depth} dim = {len(L_next)}")
        if len(L_next) == 0:
            print(f"  → L nilpotent of class {depth - 1}")
            break
        L_current = L_next


def explore_generator_structure(n_gens=4):
    """Explore full SHA: include σ_0, σ_1 effects via ROTR parts.
    σ_0 = ROTR_7 ⊕ ROTR_18 (ignoring SHR part)
    σ_1 = ROTR_17 ⊕ ROTR_19 (ignoring SHR part)

    These are partial approximations of σ.
    """
    print("\n\n=== Extended: include ROTR parts of σ_0, σ_1 ===")

    M_s0, _, _ = build_sigma_matrix([2, 13, 22], n=32)
    M_s1, _, _ = build_sigma_matrix([6, 11, 25], n=32)
    # Approximation: σ's rotation parts only (ignoring SHR)
    M_sigma0 = build_sigma_matrix([7, 18], n=32)[0]  # partial σ_0
    M_sigma1 = build_sigma_matrix([17, 19], n=32)[0]  # partial σ_1

    I = np.eye(16, dtype=np.uint8)
    Ns = [((M ^ I) & 1) for M in [M_s0, M_s1, M_sigma0, M_sigma1]]
    names = ["Σ_0 - I", "Σ_1 - I", "σ_0' - I (partial)", "σ_1' - I (partial)"]

    for name, N in zip(names, Ns):
        r = gf2_rank(N.copy())
        print(f"  rank({name}) = {r}")

    # Build full Lie algebra from 4 generators
    L = iterate_brackets(Ns, max_depth=30)
    indep = linearly_independent_subset(L)
    print(f"\n  Full 4-generator Lie algebra dimension: {len(indep)}")


if __name__ == "__main__":
    main_analysis()
    explore_generator_structure()
