"""
Session 19: Prove L_SHA is nilpotent via lower central series.

L_SHA = Z_2-Lie algebra generated by {N_Σ_0, N_Σ_1, N_σ_0, N_σ_1}
where N_* = Σ_*/σ_* - I are nilpotent operators on F_2^{32}.

STRATEGY:
1. Verify each generator is nilpotent (as matrix over F_2)
2. Build L_SHA via iterative bracket closure
3. Compute lower central series γ^k(L) = [L, γ^{k-1}(L)]
4. If γ^k(L) = 0 for some k → L is nilpotent of class k-1
"""
import numpy as np
from session_17_and import change_of_basis_x_to_s, change_of_basis_s_to_x
from session_18b_shr import shr_matrix_in_s_basis


def commutator(A, B):
    return ((A @ B) ^ (B @ A)) & 1


def matrix_rank_gf2(M):
    M = M.copy() & 1
    rows, cols = M.shape
    rank = 0
    r = 0
    for c in range(cols):
        if r >= rows: break
        pivot = None
        for rr in range(r, rows):
            if M[rr, c] == 1:
                pivot = rr; break
        if pivot is None: continue
        if pivot != r:
            M[[r, pivot]] = M[[pivot, r]]
        for rr in range(rows):
            if rr != r and M[rr, c] == 1:
                M[rr] ^= M[r]
        rank += 1
        r += 1
    return rank


def linear_span_dim(matrices):
    if not matrices:
        return 0
    vectors = np.array([m.flatten() for m in matrices], dtype=np.uint8)
    return matrix_rank_gf2(vectors)


def extend_span(basis, new_matrices):
    basis = list(basis)
    for m in new_matrices:
        if m.sum() == 0:
            continue
        test_set = basis + [m]
        if linear_span_dim(test_set) > linear_span_dim(basis):
            basis.append(m)
    return basis


def build_Lie_algebra(generators, max_iter=50):
    L = list(generators)
    for iteration in range(max_iter):
        new_elements = []
        for i, A in enumerate(L):
            for j, B in enumerate(L):
                if i < j:
                    C = commutator(A, B)
                    new_elements.append(C)
        L_before = L
        L = extend_span(L, new_elements)
        if len(L) == len(L_before):
            break
    return L, iteration


def lower_central_series(L_basis, max_iter=50):
    dims = [len(L_basis)]
    gamma_k = list(L_basis)

    for step in range(1, max_iter):
        next_gen = []
        for A in L_basis:
            for B in gamma_k:
                C = commutator(A, B)
                if C.sum() > 0:
                    next_gen.append(C)
        if not next_gen:
            dims.append(0)
            return dims
        gamma_next = extend_span([], next_gen)
        dims.append(len(gamma_next))
        if len(gamma_next) == 0:
            return dims
        gamma_k = gamma_next

    return dims


def is_nilpotent_matrix(M, max_power=32):
    N = M.copy() & 1
    current = N.copy()
    for k in range(1, max_power + 1):
        if current.sum() == 0:
            return k
        current = (current @ N) & 1
    return -1


def main_proof():
    n = 32

    def rotr_full_matrix(r, n):
        from session_14_sigma0 import lucas_expansion
        coeffs = {p: 1 for p in lucas_expansion(r, n - 1)}
        M = np.zeros((n, n), dtype=np.uint8)
        for j in range(n):
            for pos in coeffs:
                target = j + pos
                if target < n:
                    M[target, j] ^= 1
        return M

    S0 = np.zeros((n, n), dtype=np.uint8)
    for r in [2, 13, 22]:
        S0 ^= rotr_full_matrix(r, n)
    S0 &= 1

    S1 = np.zeros((n, n), dtype=np.uint8)
    for r in [6, 11, 25]:
        S1 ^= rotr_full_matrix(r, n)
    S1 &= 1

    sigma0 = np.zeros((n, n), dtype=np.uint8)
    for r in [7, 18]:
        sigma0 ^= rotr_full_matrix(r, n)
    sigma0 ^= shr_matrix_in_s_basis(3, n)
    sigma0 &= 1

    sigma1 = np.zeros((n, n), dtype=np.uint8)
    for r in [17, 19]:
        sigma1 ^= rotr_full_matrix(r, n)
    sigma1 ^= shr_matrix_in_s_basis(10, n)
    sigma1 &= 1

    I = np.eye(n, dtype=np.uint8)
    N_S0 = (S0 ^ I) & 1
    N_S1 = (S1 ^ I) & 1
    N_sigma0 = (sigma0 ^ I) & 1
    N_sigma1 = (sigma1 ^ I) & 1

    generators = [N_S0, N_S1, N_sigma0, N_sigma1]
    names = ['N_Sigma_0', 'N_Sigma_1', 'N_sigma_0', 'N_sigma_1']

    print("=== Step 1: Verify generators are nilpotent ===\n")
    all_nilp = True
    for name, N in zip(names, generators):
        k = is_nilpotent_matrix(N)
        if k > 0:
            print(f"  {name}^{k} = 0  -> nilpotent of order <= {k}")
        else:
            print(f"  {name} NOT nilpotent within {n} steps")
            all_nilp = False

    if not all_nilp:
        print("\n  Not all generators nilpotent -> Engel's theorem conditions fail.")
        print("  L_SHA may not be nilpotent.")

    print("\n=== Step 2: Build L_SHA via bracket closure ===\n")
    L, iters = build_Lie_algebra(generators, max_iter=30)
    print(f"  L_SHA dimension: {len(L)} (closure after {iters} iterations)")

    print("\n=== Step 3: Lower central series ===\n")
    dims = lower_central_series(L, max_iter=20)
    print(f"  Dimensions of gamma^k(L):")
    for i, d in enumerate(dims, 1):
        print(f"    gamma^{i}(L) dim = {d}")
        if d == 0:
            nilp_class = i - 1
            print(f"\n  -> L_SHA is NILPOTENT of class {nilp_class}")
            return nilp_class, dims

    print(f"\n  Did not terminate.")
    return None, dims


if __name__ == "__main__":
    nilp_class, dims = main_proof()
    print(f"\n=== CONCLUSION ===")
    if nilp_class is not None:
        print(f"THEOREM: L_SHA is NILPOTENT Lie algebra of class {nilp_class}.")
        print(f"Its lower central series has dimensions: {dims}")
    else:
        print(f"Lower central series did not terminate in given iterations.")
        print(f"Series so far: {dims}")
