#!/usr/bin/env python3
"""
EXP 150: ★-Polynomial Kernel — Invisible Differences

In GF(2)[x]/(x^32+1):
  ROTR_k = multiplication by x^k
  Σ₁ = multiplication by P_Σ₁ = x^6 + x^11 + x^25
  Σ₀ = multiplication by P_Σ₀ = x^2 + x^13 + x^22

If gcd(P_Σ, x^32+1) ≠ 1 → kernel exists → "invisible" differences.
These differences pass through Σ UNCHANGED → simplify collision equation.

COMPUTE:
  1. gcd(P_Σ₁, x^32+1) over GF(2)
  2. gcd(P_Σ₀, x^32+1) over GF(2)
  3. Kernel dimensions
  4. Do kernel elements survive through full SHA-256 rounds?
"""
import sys, os, random, math
import numpy as np
sys.path.insert(0, os.path.dirname(__file__))
from sha256_core import *

# ============================================================
# GF(2) POLYNOMIAL ARITHMETIC
# ============================================================
def gf2_poly_mul(a, b):
    """Multiply two GF(2) polynomials (represented as integers, bit i = coeff of x^i)."""
    result = 0
    while b:
        if b & 1:
            result ^= a
        a <<= 1
        b >>= 1
    return result

def gf2_poly_mod(a, m):
    """a mod m over GF(2)."""
    deg_m = m.bit_length() - 1
    while a.bit_length() - 1 >= deg_m and a > 0:
        a ^= m << (a.bit_length() - 1 - deg_m)
    return a

def gf2_poly_gcd(a, b):
    """GCD of two GF(2) polynomials."""
    while b:
        a, b = b, gf2_poly_mod(a, b)
    return a

def gf2_poly_deg(p):
    """Degree of GF(2) polynomial."""
    if p == 0: return -1
    return p.bit_length() - 1

def poly_to_str(p):
    """Pretty-print GF(2) polynomial."""
    if p == 0: return "0"
    terms = []
    for i in range(p.bit_length()):
        if (p >> i) & 1:
            if i == 0: terms.append("1")
            elif i == 1: terms.append("x")
            else: terms.append(f"x^{i}")
    return " + ".join(reversed(terms))

# ============================================================
# SHA-256 Σ POLYNOMIALS
# ============================================================
def compute_sigma_kernels():
    """Compute kernels of Σ₁, Σ₀, σ₀, σ₁ over GF(2)[x]/(x^32+1)."""
    print(f"\n{'='*60}")
    print(f"★-POLYNOMIAL KERNELS")
    print(f"{'='*60}")

    modulus = (1 << 32) | 1  # x^32 + 1

    # Σ₁(e) = ROTR_6(e) ⊕ ROTR_11(e) ⊕ ROTR_25(e)
    # = (x^6 + x^11 + x^25) · e
    P_Sigma1 = (1 << 6) | (1 << 11) | (1 << 25)

    # Σ₀(a) = ROTR_2(a) ⊕ ROTR_13(a) ⊕ ROTR_22(a)
    P_Sigma0 = (1 << 2) | (1 << 13) | (1 << 22)

    # σ₀(x) = ROTR_7(x) ⊕ ROTR_18(x) ⊕ SHR_3(x)
    # SHR_3 ≈ ROTR_3 (ignoring top 3 bits)
    P_sig0_approx = (1 << 7) | (1 << 18) | (1 << 3)

    # σ₁(x) = ROTR_17(x) ⊕ ROTR_19(x) ⊕ SHR_10(x)
    P_sig1_approx = (1 << 17) | (1 << 19) | (1 << 10)

    polys = [
        ("Σ₁ (round)", P_Sigma1),
        ("Σ₀ (round)", P_Sigma0),
        ("σ₀ (schedule, approx)", P_sig0_approx),
        ("σ₁ (schedule, approx)", P_sig1_approx),
    ]

    for name, P in polys:
        g = gf2_poly_gcd(P, modulus)
        ker_dim = gf2_poly_deg(g)

        print(f"\n  {name}:")
        print(f"    P = {poly_to_str(P)}")
        print(f"    gcd(P, x³²+1) = {poly_to_str(g)}")
        print(f"    Kernel dimension = {ker_dim}")

        if ker_dim > 0:
            print(f"    ★★★ KERNEL EXISTS! dim = {ker_dim}")
            print(f"    → {ker_dim}-bit invisible differences for {name}")

            # Find kernel elements
            # ker = multiples of (x^32+1)/gcd in the ring
            quotient = gf2_poly_mod(modulus, g)  # Actually need division
            # Better: kernel = {e : P·e = 0 mod (x^32+1)}
            # = {e : e ∈ ideal generated by (x^32+1)/gcd}

            # Verify by testing: does Σ(ker_element) = 0?
            print(f"    Kernel generator: (x³²+1) / gcd = ?")
        else:
            print(f"    Kernel is trivial ({name} is invertible)")

    # PRODUCTS: What about Σ₁·Σ₀ (composed)?
    P_product = gf2_poly_mod(gf2_poly_mul(P_Sigma1, P_Sigma0), modulus)
    g_prod = gf2_poly_gcd(P_product, modulus)
    print(f"\n  Σ₁·Σ₀ (product):")
    print(f"    gcd(Σ₁·Σ₀, x³²+1) = {poly_to_str(g_prod)}")
    print(f"    Kernel dimension = {gf2_poly_deg(g_prod)}")

def verify_kernel_elements(N=1000):
    """Verify kernel elements experimentally."""
    print(f"\n{'='*60}")
    print(f"KERNEL VERIFICATION")
    print(f"{'='*60}")

    modulus = (1 << 32) | 1
    P_Sigma1 = (1 << 6) | (1 << 11) | (1 << 25)
    g = gf2_poly_gcd(P_Sigma1, modulus)
    ker_dim = gf2_poly_deg(g)

    if ker_dim <= 0:
        print(f"  No kernel for Σ₁ (invertible)")
        # But let's check: does Σ₁ have low-weight outputs for specific inputs?
        print(f"\n  Low-weight outputs of Σ₁:")
        min_hw_sigma1 = 32
        min_input = 0
        for _ in range(N):
            e = random.randint(1, MASK)
            s = sigma1(e)
            h = hw(s)
            if h < min_hw_sigma1:
                min_hw_sigma1 = h
                min_input = e

        print(f"    min HW(Σ₁(e)) = {min_hw_sigma1} (for e=0x{min_input:08x})")

        # For comparison: random function
        min_hw_random = 32
        for _ in range(N):
            min_hw_random = min(min_hw_random, hw(random.randint(0, MASK)))
        print(f"    min HW(random) = {min_hw_random}")

        # Exhaustive for small: find THE minimum
        print(f"\n  Exhaustive search for low HW(Σ₁(e)):")
        hw_dist = [0] * 33
        for e in range(min(2**20, 2**32)):
            h = hw(sigma1(e))
            hw_dist[h] += 1

        for h in range(10):
            if hw_dist[h] > 0:
                print(f"    HW={h}: {hw_dist[h]} inputs")

    # Same for Σ₀
    P_Sigma0 = (1 << 2) | (1 << 13) | (1 << 22)
    g0 = gf2_poly_gcd(P_Sigma0, modulus)
    ker_dim_0 = gf2_poly_deg(g0)

    if ker_dim_0 > 0:
        print(f"\n  Σ₀ has kernel of dimension {ker_dim_0}!")
    else:
        print(f"\n  Σ₀ also invertible")

    # Check factorization of x^32 + 1 over GF(2)
    print(f"\n  Factorization of x³²+1 over GF(2):")
    print(f"    x³²+1 = (x+1)^32 in GF(2)? ", end="")
    # Check: (x+1)^32 mod 2 = x^32 + 1 (by Frobenius)
    test = 1
    xp1 = 0b11  # x + 1
    for _ in range(32):
        test = gf2_poly_mul(test, xp1)
    if test == modulus:
        print("YES!")
        print(f"    x³²+1 = (x+1)³² — PERFECT POWER!")
        print(f"    This means: GF(2)[x]/(x³²+1) is a LOCAL ring")
        print(f"    (x+1) is the ONLY prime factor")
        print(f"    Every polynomial P with P(1) = 0 shares factor (x+1)")
    else:
        print(f"NO (test = {poly_to_str(test)})")

    # Check: P_Σ₁(1) = ?
    # Evaluate at x=1: 1^6 + 1^11 + 1^25 = 1 + 1 + 1 = 1 (odd) in GF(2)
    # So P_Σ₁(1) = 1 ≠ 0 → (x+1) does NOT divide P_Σ₁
    p1_sigma1 = bin(P_Sigma1).count('1') % 2
    p1_sigma0 = bin(P_Sigma0).count('1') % 2
    print(f"\n  P_Σ₁(1) = {p1_sigma1} (number of terms mod 2)")
    print(f"  P_Σ₀(1) = {p1_sigma0}")

    if p1_sigma1 == 0:
        print(f"  P_Σ₁(1) = 0 → (x+1) divides P_Σ₁ → KERNEL EXISTS!")
    else:
        print(f"  P_Σ₁(1) = 1 → (x+1) does NOT divide P_Σ₁")

    if p1_sigma0 == 0:
        print(f"  P_Σ₀(1) = 0 → (x+1) divides P_Σ₀ → KERNEL EXISTS!")
    else:
        print(f"  P_Σ₀(1) = 1 → (x+1) does NOT divide P_Σ₀")

    # KEY: Check higher powers of (x+1)
    print(f"\n  Divisibility by (x+1)^k:")
    for name, P in [("Σ₁", P_Sigma1), ("Σ₀", P_Sigma0)]:
        xp1_power = 0b11  # (x+1)
        for k in range(1, 33):
            if gf2_poly_mod(P, xp1_power) == 0:
                print(f"    {name}: divisible by (x+1)^{k}")
            else:
                print(f"    {name}: NOT divisible by (x+1)^{k} (max k={k-1})")
                break
            xp1_power = gf2_poly_mul(xp1_power, 0b11)

def test_polynomial_attack():
    """Can polynomial structure be used for attack?"""
    print(f"\n{'='*60}")
    print(f"POLYNOMIAL ATTACK IMPLICATIONS")
    print(f"{'='*60}")

    # If Σ functions are invertible: no null differences
    # But they might have LOW-WEIGHT differences:
    # δe such that HW(Σ₁(δe)) is small → small contribution to δT1

    # Find: which δe minimizes HW(Σ₁(δe))?
    print(f"\n  Minimum-weight Σ₁ outputs:")
    best = []
    for hw_target in range(1, 8):
        count = 0
        for delta_e in range(1, 2**20):  # Sample
            if hw(delta_e) > 5: continue  # Sparse input
            s = sigma1(delta_e)
            if hw(s) <= hw_target:
                count += 1
                if len(best) < 5:
                    best.append((hw(s), hw(delta_e), delta_e, s))

    best.sort()
    print(f"    HW(Σ₁(δe)) | HW(δe) | δe")
    print(f"    " + "-" * 40)
    for hw_out, hw_in, de, s in best[:8]:
        print(f"    {hw_out:>11} | {hw_in:>6} | 0x{de:08x} → 0x{s:08x}")

    # Same for Σ₀
    print(f"\n  Minimum-weight Σ₀ outputs:")
    best0 = []
    for delta_a in range(1, 2**20):
        if hw(delta_a) > 5: continue
        s = sigma0(delta_a)
        if hw(s) <= 5:
            best0.append((hw(s), hw(delta_a), delta_a, s))

    best0.sort()
    for hw_out, hw_in, da, s in best0[:8]:
        print(f"    HW(Σ₀(δa))={hw_out}, HW(δa)={hw_in}: "
              f"0x{da:08x} → 0x{s:08x}")

    # What's the minimum WEIGHT RATIO?
    print(f"\n  Weight expansion ratio HW(Σ(δ))/HW(δ):")
    ratios_1 = []; ratios_0 = []
    for _ in range(10000):
        de = random.randint(1, MASK)
        ratios_1.append(hw(sigma1(de)) / max(hw(de), 1))
        ratios_0.append(hw(sigma0(de)) / max(hw(de), 1))

    r1 = np.array(ratios_1); r0 = np.array(ratios_0)
    print(f"    Σ₁: min_ratio={r1.min():.3f}, avg={r1.mean():.3f}")
    print(f"    Σ₀: min_ratio={r0.min():.3f}, avg={r0.mean():.3f}")

def main():
    random.seed(42)
    print("=" * 60)
    print("EXP 150: ★-POLYNOMIAL KERNEL")
    print("Invisible differences through Σ functions")
    print("=" * 60)

    compute_sigma_kernels()
    verify_kernel_elements(500)
    test_polynomial_attack()

    print(f"\n{'='*60}")
    print(f"VERDICT")
    print(f"{'='*60}")

if __name__ == "__main__":
    main()
