"""
Session 10: Extract minimal ideal decomposition of D^4.

After Session 9 found D^4 NOT simple (proper ideals of dim 45, 55, 65, 75 exist),
extract complete decomposition:

1. For each basis element x_i: compute ideal_i = ideal generated by x_i.
2. Cluster: which basis elements give same/equivalent ideal?
3. Find minimal distinct ideals I_1, I_2, ..., I_m.
4. Test direct sum: dim(I_1) + ... + dim(I_m) = 264?
   If yes → D^4 = ⊕ I_i (semisimple structure).
5. Compute brackets [I_a, I_b] for a ≠ b. If all zero → strong direct sum (each I_i is ideal).

Optimization: precompute adjoint matrices ad_i (264 × 264 over F_2),
avoid einsum by using direct matrix-vector multiplies.
"""

import sys
import time
sys.path.insert(0, '/home/user/SHA-256/research/prismatic')

import numpy as np
from session_21_perfect import extract_perfect_subalgebra
from session_20b_derived import GF2Basis


def setup_basis_resolver(D4):
    n = 264
    BT = np.array([m.flatten() for m in D4], dtype=np.uint8)
    work = BT.copy()
    T = np.eye(n, dtype=np.uint8)
    pivot_cols = []
    row = 0
    for col in range(BT.shape[1]):
        if row >= n:
            break
        pivots_in_col = np.where(work[row:, col] == 1)[0]
        if len(pivots_in_col) == 0:
            continue
        pivot = row + pivots_in_col[0]
        if pivot != row:
            work[[row, pivot]] = work[[pivot, row]]
            T[[row, pivot]] = T[[pivot, row]]
        ones_mask = work[:, col] == 1
        ones_mask[row] = False
        if ones_mask.any():
            work[ones_mask] ^= work[row]
            T[ones_mask] ^= T[row]
        pivot_cols.append(col)
        row += 1
    return np.array(pivot_cols), T


def precompute_ad_matrices(C):
    """For each i, precompute ad_i ∈ F_2^{264×264}: (ad_i)[k, l] = C[i, l, k].
    Then ad_i @ y (mod 2) gives coefficient vector of [x_i, y]."""
    n = C.shape[0]
    ad = np.zeros((n, n, n), dtype=np.uint8)
    for i in range(n):
        # ad[i][k, l] = coefficient of x_k in [x_i, x_l]
        # That's C[i, l, k]
        ad[i] = C[i].T  # C[i] is (l, k); transpose gives (k, l)
    return ad


def compute_ideal_orbit_ad(x_coeffs, ad, max_iter=20):
    """Optimized: use precomputed ad matrices.
    ad: (264, 264, 264), ad[i] @ y = [x_i, y] coefficients (over F_2)."""
    n = ad.shape[0]
    ideal = GF2Basis(n)
    ideal.add(x_coeffs)
    frontier = [x_coeffs.copy()]
    for it in range(max_iter):
        new_elements = []
        for y in frontier:
            # All [x_i, y] for i = 0..263 — use ad matrices
            # ad[i] @ y gives bracket. Stack as ad @ y (vectorized over i).
            brackets = (ad.reshape(n*n, n) @ y.astype(np.int32)).reshape(n, n) & 1
            brackets = brackets.astype(np.uint8)
            for k in range(n):
                row = brackets[k]
                if row.sum() == 0:
                    continue
                added, _ = ideal.add(row)
                if added:
                    new_elements.append(row.copy())
        frontier = new_elements
        if not frontier:
            break
    return ideal


def ideal_basis_as_set(ideal):
    """Convert GF2Basis to canonical form: sorted tuple of bytes."""
    return frozenset(tuple(b.tobytes()) for b in ideal.basis)


def compute_brackets_between_ideals(I_a_basis, I_b_basis, ad):
    """Compute [I_a, I_b] as set of brackets, return spanning vectors."""
    n = ad.shape[0]
    result = []
    for u in I_a_basis:
        # ad_u(v) = bracket using u as "first" element
        # But ad is indexed by single element — for arbitrary u as combination,
        # need to compute bracket directly.
        # [u, v] = sum_i u[i] * (ad_i @ v)
        nonzero_u = np.where(u == 1)[0]
        for v in I_b_basis:
            if len(nonzero_u) == 0:
                continue
            # bracket = sum over i in nonzero_u of (ad[i] @ v)
            ad_subset = ad[nonzero_u]  # (k, 264, 264) where k = |nonzero_u|
            partials = (ad_subset.reshape(-1, n) @ v.astype(np.int32)).reshape(len(nonzero_u), n) & 1
            bracket = partials.sum(axis=0) & 1
            if bracket.sum() > 0:
                result.append(bracket.astype(np.uint8))
    return result


def main():
    print("=== Session 10: D^4 minimal ideal decomposition ===\n")

    print("Step 1: Setup")
    start = time.time()
    D4 = extract_perfect_subalgebra()
    n = len(D4)
    pivot_cols, T = setup_basis_resolver(D4)
    C = np.load('/home/user/SHA-256/research/composition_lemma/struct_constants.npy')
    print(f"  D^4 dim {n}, structure constants loaded ({time.time()-start:.1f}s)")

    print("\nStep 2: Precompute adjoint matrices ad_i")
    ad = precompute_ad_matrices(C)
    print(f"  ad shape {ad.shape} ({time.time()-start:.1f}s)")

    print("\nStep 3: Compute ideal generated by each basis element")
    start = time.time()
    ideal_data = []  # list of (i, dim, basis_signature)

    for i in range(n):
        x_coeffs = np.zeros(n, dtype=np.uint8)
        x_coeffs[i] = 1
        ideal = compute_ideal_orbit_ad(x_coeffs, ad, max_iter=20)
        d = ideal.size()
        sig = ideal_basis_as_set(ideal)
        ideal_data.append((i, d, sig, ideal.basis))
        if i % 30 == 0:
            elapsed = time.time() - start
            eta = elapsed / (i + 1) * (n - i - 1)
            print(f"    Progress i={i}/{n}, elapsed={elapsed:.1f}s, ETA={eta:.1f}s")

    elapsed = time.time() - start
    print(f"  264 ideals computed in {elapsed:.1f}s")

    print("\nStep 4: Cluster ideals by signature (same span)")
    # Group basis elements by which ideal they generate
    sig_to_indices = {}
    sig_to_dim = {}
    sig_to_basis = {}
    for i, d, sig, ideal_basis in ideal_data:
        if sig not in sig_to_indices:
            sig_to_indices[sig] = []
            sig_to_dim[sig] = d
            sig_to_basis[sig] = ideal_basis
        sig_to_indices[sig].append(i)

    print(f"  Distinct ideals found: {len(sig_to_indices)}")
    sorted_sigs = sorted(sig_to_indices.keys(), key=lambda s: sig_to_dim[s])
    for j, sig in enumerate(sorted_sigs):
        indices = sig_to_indices[sig]
        d = sig_to_dim[sig]
        print(f"    Ideal {j}: dim {d}, generated by {len(indices)} basis elements (e.g., x_{indices[0]})")

    print("\nStep 5: Identify minimal ideals")
    # An ideal I is minimal if no proper sub-ideal exists.
    # In our context: minimal = smallest in inclusion order.
    # We can detect inclusions by checking if basis of I_a ⊆ I_b.

    sigs_by_dim = sorted(sorted_sigs, key=lambda s: sig_to_dim[s])
    minimal_sigs = []
    for sig in sigs_by_dim:
        is_minimal = True
        for smaller_sig in minimal_sigs:
            if sig_to_dim[smaller_sig] >= sig_to_dim[sig]:
                continue
            # Check if smaller_sig ⊆ sig
            # Build basis matrix of sig and check if all smaller basis vectors lie in span
            sig_basis_mat = np.array(sig_to_basis[sig])
            checker = GF2Basis(264)
            for v in sig_basis_mat:
                checker.add(v)
            all_contained = True
            for v_small in sig_to_basis[smaller_sig]:
                # v_small contained iff after adding to checker, dim doesn't grow
                d_before = checker.size()
                checker.add(v_small.copy())
                if checker.size() > d_before:
                    all_contained = False
                    # Restore — but GF2Basis has no remove. Just rebuild.
                    checker = GF2Basis(264)
                    for v in sig_basis_mat:
                        checker.add(v)
                    break
            if all_contained:
                is_minimal = False
                break
        if is_minimal:
            minimal_sigs.append(sig)

    print(f"  Minimal distinct ideals: {len(minimal_sigs)}")
    minimal_dims = [sig_to_dim[s] for s in minimal_sigs]
    print(f"  Minimal ideal dimensions: {sorted(minimal_dims)}")
    print(f"  Sum of minimal dims: {sum(minimal_dims)}")
    print(f"  Total D^4 dim: {n}")

    print("\nStep 6: Test direct sum decomposition")
    if sum(minimal_dims) == n:
        print(f"  ✓ Sum of minimal dims = 264 (matches D^4 dim)")
        print(f"  → Possible direct sum decomposition")
    else:
        print(f"  ✗ Sum {sum(minimal_dims)} ≠ 264")
        print(f"  → NOT direct sum of minimal ideals — overlap or radical exists")

    # Test pairwise intersection
    print("\nStep 7: Pairwise intersection of minimal ideals (over F_2)")
    if len(minimal_sigs) <= 8:  # only for small numbers
        all_zero_intersect = True
        for a in range(len(minimal_sigs)):
            for b in range(a+1, len(minimal_sigs)):
                I_a = sig_to_basis[minimal_sigs[a]]
                I_b = sig_to_basis[minimal_sigs[b]]
                # Intersection: combined basis - sum = intersection dim by dimension formula
                combined = GF2Basis(n)
                for v in I_a:
                    combined.add(v.copy())
                for v in I_b:
                    combined.add(v.copy())
                d_a = sig_to_dim[minimal_sigs[a]]
                d_b = sig_to_dim[minimal_sigs[b]]
                d_sum = combined.size()
                d_intersect = d_a + d_b - d_sum
                if d_intersect > 0:
                    all_zero_intersect = False
                    print(f"    I_{a} (dim {d_a}) ∩ I_{b} (dim {d_b}) = dim {d_intersect}")
        if all_zero_intersect:
            print(f"    All pairwise intersections = 0 — direct sum confirmed!")

    print("\nStep 8: Test [I_a, I_b] = 0 for a ≠ b (independence)")
    # If I_a, I_b are different MINIMAL ideals in semisimple algebra: [I_a, I_b] ⊆ I_a ∩ I_b = 0.
    if len(minimal_sigs) <= 8:
        for a in range(len(minimal_sigs)):
            for b in range(a+1, len(minimal_sigs)):
                I_a = sig_to_basis[minimal_sigs[a]]
                I_b = sig_to_basis[minimal_sigs[b]]
                brackets = compute_brackets_between_ideals(I_a, I_b, ad)
                if brackets:
                    nonzero = sum(1 for B in brackets if B.sum() > 0)
                    print(f"    [I_{a}, I_{b}]: {nonzero} non-zero brackets out of {len(brackets)}")
                    if nonzero > 0:
                        # Check if brackets are в I_a or I_b (ideal property)
                        ck_a = GF2Basis(n)
                        for v in I_a:
                            ck_a.add(v.copy())
                        ck_b = GF2Basis(n)
                        for v in I_b:
                            ck_b.add(v.copy())
                        in_a = sum(1 for B in brackets if (ck_a.add(B.copy())[0] == False))
                        ck_a = GF2Basis(n)
                        for v in I_a:
                            ck_a.add(v.copy())
                        in_b = sum(1 for B in brackets if (ck_b.add(B.copy())[0] == False))
                        ck_b = GF2Basis(n)
                        for v in I_b:
                            ck_b.add(v.copy())
                        print(f"      In I_{a}: {in_a}, in I_{b}: {in_b}")
                else:
                    print(f"    [I_{a}, I_{b}] = 0 — ideals commute")

    # Save minimal ideal bases
    print("\nStep 9: Save minimal ideal bases")
    minimal_save = {f"ideal_{j}": np.array(sig_to_basis[s]) for j, s in enumerate(minimal_sigs)}
    np.savez('/home/user/SHA-256/research/composition_lemma/minimal_ideals.npz', **minimal_save)
    print(f"  Saved {len(minimal_save)} minimal ideal bases to minimal_ideals.npz")


if __name__ == "__main__":
    main()
