"""
Session 10b: Fast decomposition using known proper-ideal indices from Session 9b.

From Session 9b log: 47 basis indices give proper ideals (dims 45/55/65/75).
Other 217 give full D^4 (264). So minimal ideals must come from these 47.

Strategy:
1. Compute ideal generated by each of 47 known problematic indices.
2. Cluster by exact span (not just dim).
3. Identify minimal distinct ideals.
4. Check direct sum: sum of minimal dims = 264?
5. Test if minimal ideals are pairwise commuting ([I_a, I_b] = 0).

Optimization: small number of ideals to compute, using precomputed ad matrices.
Output unbuffered, written to file for live progress.
"""

import sys
import time
import os
sys.path.insert(0, '/home/user/SHA-256/research/prismatic')

import numpy as np
from session_21_perfect import extract_perfect_subalgebra
from session_20b_derived import GF2Basis


# Known proper-ideal indices from Session 9b log (47 elements)
PROPER_INDICES = [0, 1, 3, 5, 8, 12, 17, 24, 25, 26, 29, 30, 33, 34, 35, 36,
                   37, 41, 44, 54, 63, 64, 68, 70, 71, 74, 76, 90, 91, 95, 97,
                   104, 112, 120, 121, 135, 138, 155, 157, 160, 162, 170, 190,
                   197, 216, 219, 256]

LOG_FILE = '/home/user/SHA-256/research/composition_lemma/session_10b_log.txt'


def log(msg):
    print(msg, flush=True)
    with open(LOG_FILE, 'a') as f:
        f.write(msg + '\n')


def setup_basis_resolver(D4):
    n = 264
    BT = np.array([m.flatten() for m in D4], dtype=np.uint8)
    work = BT.copy()
    T = np.eye(n, dtype=np.uint8)
    pivot_cols = []
    row = 0
    for col in range(BT.shape[1]):
        if row >= n:
            break
        pivots_in_col = np.where(work[row:, col] == 1)[0]
        if len(pivots_in_col) == 0:
            continue
        pivot = row + pivots_in_col[0]
        if pivot != row:
            work[[row, pivot]] = work[[pivot, row]]
            T[[row, pivot]] = T[[pivot, row]]
        ones_mask = work[:, col] == 1
        ones_mask[row] = False
        if ones_mask.any():
            work[ones_mask] ^= work[row]
            T[ones_mask] ^= T[row]
        pivot_cols.append(col)
        row += 1
    return np.array(pivot_cols), T


def compute_ideal_via_ad(x_coeffs, ad_flat, n=264, max_iter=20):
    """ad_flat shape (264*264, 264) for fast matmul."""
    ideal = GF2Basis(n)
    ideal.add(x_coeffs.copy())
    frontier = [x_coeffs.copy()]
    for it in range(max_iter):
        new_elements = []
        for y in frontier:
            # Brackets [x_i, y] for all i = 0..263
            # ad_flat[i * n + k, l] * y[l] sum over l → bracket[i, k]
            # i.e., (ad_flat @ y).reshape(n, n) gives bracket matrix
            br = (ad_flat @ y.astype(np.int32)) & 1  # shape (n*n,)
            br = br.reshape(n, n).astype(np.uint8)
            # Each row k is [x_k, y]'s coefficient vector? No wait.
            # ad[i] is (n, n) where (ad[i])[k, l] = C[i, l, k]
            # ad[i] @ y gives bracket [x_i, y] in coords... let me re-check.
            #
            # [x_i, y] = sum_j y[j] [x_i, x_j] = sum_j y[j] sum_k C[i,j,k] x_k
            # In coords: ([x_i, y])[k] = sum_j y[j] C[i, j, k]
            # If ad[i, k, l] = C[i, l, k], then (ad[i] @ y)[k] = sum_l ad[i, k, l] y[l] = sum_l C[i, l, k] y[l]
            # That equals sum_j y[j] C[i, j, k] (renaming l → j) ✓
            # So br[i, :] = bracket [x_i, y] coefficients ✓

            for i in range(n):
                row = br[i]
                if row.sum() == 0:
                    continue
                added, _ = ideal.add(row)
                if added:
                    new_elements.append(row.copy())
        frontier = new_elements
        if not frontier:
            break
    return ideal


def basis_signature(ideal):
    """Canonical signature for ideal — sorted tuple of basis vectors as bytes.
    Two ideals have same signature iff same span (since GF2Basis stores reduced form)."""
    sorted_basis = sorted(b.tobytes() for b in ideal.basis)
    return tuple(sorted_basis)


def main():
    # Truncate log file
    with open(LOG_FILE, 'w') as f:
        f.write('')

    log("=== Session 10b: Fast decomposition using Session 9b indices ===\n")

    log("Step 1: Setup")
    start = time.time()
    D4 = extract_perfect_subalgebra()
    n = len(D4)
    pivot_cols, T = setup_basis_resolver(D4)
    log(f"  D^4 dim {n} ({time.time()-start:.1f}s)")

    C = np.load('/home/user/SHA-256/research/composition_lemma/struct_constants.npy')
    log(f"  Structure constants loaded {C.shape}")

    log("\nStep 2: Build ad matrices, flatten for fast matmul")
    # ad[i, k, l] = C[i, l, k] → reshape to (n*n, n)
    ad = np.transpose(C, (0, 2, 1))  # (i, k, l) where ad[i, k, l] = C[i, l, k]
    ad_flat = ad.reshape(n*n, n)
    log(f"  ad_flat shape {ad_flat.shape} ({time.time()-start:.1f}s)")

    log(f"\nStep 3: Compute ideal for each of {len(PROPER_INDICES)} known proper-ideal indices")
    ideals_data = []  # (index, dim, basis_list, signature)
    for idx, i in enumerate(PROPER_INDICES):
        x = np.zeros(n, dtype=np.uint8)
        x[i] = 1
        t0 = time.time()
        ideal = compute_ideal_via_ad(x, ad_flat, n=n, max_iter=20)
        sig = basis_signature(ideal)
        ideals_data.append((i, ideal.size(), [b.copy() for b in ideal.basis], sig))
        log(f"  i={i}: dim={ideal.size()}, time={time.time()-t0:.1f}s ({idx+1}/{len(PROPER_INDICES)})")

    log(f"\nStep 4: Cluster by signature")
    # Group by signature
    sig_groups = {}  # sig -> list of (i, dim, basis)
    for i, d, basis, sig in ideals_data:
        if sig not in sig_groups:
            sig_groups[sig] = []
        sig_groups[sig].append((i, d, basis))

    log(f"  Distinct ideals (by exact span): {len(sig_groups)}")
    cluster_summary = []
    for sig, members in sig_groups.items():
        dim_val = members[0][1]
        indices = [m[0] for m in members]
        cluster_summary.append((dim_val, indices, members[0][2]))
        log(f"    dim {dim_val}: from indices {indices}")

    log(f"\nStep 5: Identify minimal ideals (sub-ideals of others removed)")
    cluster_summary.sort(key=lambda x: x[0])  # sort by dim
    minimal_clusters = []
    for dim_val, indices, basis in cluster_summary:
        # Is this contained in any LARGER cluster already in minimal_clusters?
        is_subset = False
        for big_dim, big_idx, big_basis in minimal_clusters:
            if big_dim < dim_val:
                continue  # smaller, can't contain
            # Check if all vectors of "basis" are in span of big_basis
            checker = GF2Basis(n)
            for v in big_basis:
                checker.add(v.copy())
            d_big = checker.size()
            for v in basis:
                checker.add(v.copy())
            if checker.size() == d_big:  # nothing added → contained
                is_subset = True
                break
        if not is_subset:
            minimal_clusters.append((dim_val, indices, basis))

    log(f"  Minimal distinct ideals: {len(minimal_clusters)}")
    for dim_val, indices, basis in minimal_clusters:
        log(f"    Minimal: dim {dim_val} from indices {indices[:5]}{'...' if len(indices) > 5 else ''}")

    log(f"\nStep 6: Test direct-sum decomposition")
    # Compute span of all minimal ideals together
    combined = GF2Basis(n)
    for dim_val, indices, basis in minimal_clusters:
        for v in basis:
            combined.add(v.copy())
    sum_dim = sum(d for d, _, _ in minimal_clusters)
    union_dim = combined.size()
    log(f"  Sum of minimal dims: {sum_dim}")
    log(f"  Span union dim: {union_dim}")
    log(f"  D^4 dim: {n}")
    if sum_dim == union_dim:
        log(f"  ✓ Pairwise zero intersection (sum = union)")
        if union_dim == n:
            log(f"  ★★★ DIRECT SUM CONFIRMED: D^4 = ⊕ I_i with sum = 264")
        else:
            log(f"  ⚠ Direct sum but doesn't fill D^4 — radical of dim {n - union_dim}?")
    else:
        log(f"  ✗ Overlap detected: sum {sum_dim} > union {union_dim}, overlap {sum_dim - union_dim}")

    log(f"\nStep 7: Pairwise bracket [I_a, I_b] check")
    if len(minimal_clusters) <= 6:
        for a in range(len(minimal_clusters)):
            for b in range(a+1, len(minimal_clusters)):
                I_a_basis = minimal_clusters[a][2]
                I_b_basis = minimal_clusters[b][2]
                # [I_a, I_b]: compute brackets between basis pairs
                # [u, v] coords: sum_i u[i] * (ad[i] @ v) — using ad_flat for speed
                # For one pair: ~n^2 ops via slicing
                all_zero = True
                nonzero_count = 0
                for u in I_a_basis:
                    nonzero_u = np.where(u == 1)[0]
                    if len(nonzero_u) == 0:
                        continue
                    for v in I_b_basis:
                        if v.sum() == 0:
                            continue
                        # bracket = sum_i u[i] (ad[i] @ v) — over F_2
                        ad_subset_flat = ad_flat[(nonzero_u[:, None] * n + np.arange(n)[None, :]).flatten()]
                        partials = (ad_subset_flat @ v.astype(np.int32)) & 1
                        partials = partials.reshape(len(nonzero_u), n)
                        bracket = partials.sum(axis=0) & 1
                        if bracket.sum() > 0:
                            all_zero = False
                            nonzero_count += 1
                if all_zero:
                    log(f"    [I_{a}, I_{b}] = 0 (commuting, semisimple property)")
                else:
                    log(f"    [I_{a}, I_{b}] ≠ 0: {nonzero_count} non-trivial brackets")
    else:
        log(f"  Too many ideals ({len(minimal_clusters)}) for pairwise — skip")

    log(f"\nStep 8: Save decomposition")
    save_dict = {f"ideal_{j}_dim{d}": np.array(b) for j, (d, _, b) in enumerate(minimal_clusters)}
    np.savez('/home/user/SHA-256/research/composition_lemma/decomposition.npz', **save_dict)
    log(f"  Saved {len(save_dict)} minimal ideals to decomposition.npz")

    log(f"\nTotal wall time: {time.time()-start:.1f}s")


if __name__ == "__main__":
    main()
